### ISSUE TITLE
Rework the CSS

### ISSUE THREAD

**Issue by Drup** [ocaml/ocamlunix#3]
This CSS might be pretty, but I'm going to explain my grudge [in one screenshot](http://i.imgur.com/3CypWSk.png).

Also, pure white is not the most appropriate for reading, especially on screens. I understand that white is more elegant, but a slightly tainted color is easier on the eyes.

**Comment by dbuenzli** [comment]
Le mercredi, 29 octobre 2014 à 14:04, Gabriel Radanne a écrit :

> This CSS may be pretty, but I'm going to explain my grudge in one screenshot (http://i.imgur.com/3CypWSk.png).

What's the problem ?  

Daniel

**Comment by Drup** [comment]
The fact that the text occupy less than a fifth^W quarter of the width of my screen, and in small letters, and not even in the center.

**Comment by dbuenzli** [comment]
The base font size maybe a little bit small, maybe it could afford moving from 9pt to 10pt. But it also depends on your screen, you still want to have enough _vertical_ reading context on laptops. The good news is that the stylesheet is entirely done in relative mode, so just use the zooming function of your browser to adjust the font size to your taste, the layout should adapt to the new size.

The fact the text occupies less than a fifth of the page is related to the font size, the page width accomodates ~75 characters. You don't want to make lines stretch arbitrarily long as this hampers readability (becomes hard to go from one line to the other). 

As for centering text on pages that's completely debatable. The annoying thing with centering is that the text block moves while you resize your window which may make you loose your focus of attention. By having a fixed left margin you get a predictable location for the text block which I find is a good property for something like a book.

**Comment by Drup** [comment]
You can make the font size depends on the screen size.
On top of that, with the current font, the interline is far too big when you zoom, making it annoying to read.

~75 char is adapted to books, not screen reading.

> The annoying thing with centering is that the text block moves while you resize your window which may make you loose your focus of attention. 

You're the first person I see resizing your window _while reading_. I'm pretty sure it's specific to you, and not the general user. It would be debatable with a fixed table of content alongside the document, (like in opam doc, for example) but it's not the case here (that wouldn't be a bad idea, though).

The current html version is _harder_ to read than the pdf on screen wider than a stamp.

**Comment by dbuenzli** [comment]
Le mercredi, 29 octobre 2014 à 16:30, Gabriel Radanne a écrit :

> ~75 char is adapted to books, not screen reading.

Basic typographic rules remain the same for digital and print. A lot of people have hard time understanding that.

> You're the first person I see resizing your window while reading. I'm pretty sure it's specific to you, and not the general user.  
> Show me the data. It happens very often that I manipulate my window while focusing somewhere else and I suspect most other individuals do (if only to check that the resizing brings you what you want). Besides there's also the interaction where you switch to another tab, resize there for some reason and come back to your tab. With a fixed left margin you know deterministically where the text will be when you come back. I really don't understand what centering the text brings you here.

Daniel

**Comment by Drup** [comment]
> Basic typographic rules remain the same for digital and print. A lot of people have hard time understanding that.

No, they must be adapted, and a lot of typography enthusiasts have hard time understand that. 
The size of the medium is not fixed anymore and the way of consumption is not the same. I can get much closer to a book/paper than to a screen, hence the possibility to put small fonts, which cause the necessity to use short lines. On a screen, you can keep reading comfort even on something closer to 90 chars/line, as long as you put a font not ridiculously small. Which brings me to a remark I already made: "You can make the font size depends on the screen size. On top of that, with the current font, the interline is far too big when you zoom, making it annoying to read."

> if only to check that the resizing brings you what you want 

Yes, sure, you're totally doing that while reading a book online.

I've never even seen people using a non-maximized browser. And yes, it's not hard data, it's only circumstantial evidences. 

You know, I don't want to change the layout on your tiny little laptop, I just want you to fix it for big screens.

**Comment by dbuenzli** [comment]
Le jeudi, 30 octobre 2014 à 00:07, Gabriel Radanne a écrit :

> No, they must be adapted, and a lot of typography enthusiast have hard time understand that.

I'm impressed by your authority. The fact the canvas may be fluid doesn't change basic human factors like long lines hampering readability and basic thumb rules like keeping the measure between 45 to 90 characters or 2-3 alphabets according to your font still hold.

> On top of that, with the current font, the interline is far too big when you zoom, making it annoying to read."
> I just checked in a few different browsers. I don't see that. I'd rather say that the justification, makes it a little bit ugly in certain browsers, it should be ragged right.
> 
> Yes, sure, you're totally doing that while reading a book online. I've never even seen people using a non-maximized browser.
> Many pages fail to set a correct fluid line length for their text blocks (i.e. they don't know about `{min,max}-width` e.g. wikipedia, caml.inria.fr, ocamldoc's default style), which means that you do have to resize you browser window to impose a readable line length. Besides that still doesn't tell me why the page should be centered (but you know what: I'm not interested).  

Just a hint, if you interact with people try to understand what they tell you. To me you just look idiotic, ignorant and narrow minded – it's not the first time – that certainly won't help me listening to you.

Bye,

Daniel

**Comment by Drup** [comment]
> Just a hint, if you interact with people try to understand what they tell you. To me you just look idiotic, ignorant and narrow minded – it's not the first time – that certainly won't help me listening to you. 

Unfortunately, the feeling is quite mutual. I may appreciate your libraries, but I dislike how you work with others in an open source environment. I have had no issue to interact with lot's of other people, so even if I'm quite blunt, the problem may not be only on my end. 

But, message acknowledged, I'll be idiotic elsewhere. :)
